### ISSUE TITLE
Update Base github name

### ISSUE THREAD

**Issue by sailingsam** [sailingsam/House-Arena_frontend#13]
## Issue Description

Previously Github repo name was '**house_arena_react-vite**' which is now updated to '**House-Arena_frontend**'.
So we need to update every file where old name is used to new one.

eg, update this link in readme **https://github.com/sailingsam/house_arena_react-vite** to -> **https://github.com/sailingsam/House-Arena_frontend**

## Steps
You can use search feature on VS code (ctrl+shift+F) to directly search for every location where there is **house_arena_react-vite** and then just replace it.

**Comment by vangelif** [comment]
You could review changes [here](https://github.com/sailingsam/House-Arena_frontend/pull/15)
