### ISSUE TITLE
Optimize date code

### ISSUE THREAD

**Issue by sailingsam** [sailingsam/House-Arena_frontend#14]
## Issue Description

In the past events table after fetching the date I wrote some waste code for formatting date (eg. from API i get date as '**2024-02-27T00:00:00.000Z**' but shown date is -> '**27-02-2024**')

We can use inbuilt functions from JS for formatting of date.

## Actual Code

![Screenshot from 2024-08-10 21-53-33](https://github.com/user-attachments/assets/ef379854-1d5b-4a25-8cd6-a32a4bb99ab4)

**Comment by ruthwikchikoti** [comment]
Hey @sailingsam, please assign this issue to me!
