### ISSUE TITLE
Bring Symmetry in House names in home page

### ISSUE THREAD

**Issue by sailingsam** [sailingsam/House-Arena_frontend#17]
![Screenshot from 2024-08-23 22-43-33](https://github.com/user-attachments/assets/aa78044d-c12d-4bb5-a859-d45f2dd1be7b)

## Issue Description
- For eg. implement a line break between 'house of' and 'Leo', you have to do this for all 4 houses so that there is symmetry in house names' component height.

## Expected Behavior
- expected behaviour is like how it is visible for hose of phoenix and tusker.

## Additional Information
- read contributing guidelines before you start working on it, you can also contact me for help.

**Comment by AnujChitari** [comment]
in which file do the changes needs to be done ?
